#!/bin/sh

if [ "X$OS" != "X" ] && echo "$OS" | grep -q '`'
then
    OS=
fi

if [ "X$OS" = "X" ]
then	OS=bloat-os
    MACHINE=`uname -m | sed -e 's/ //g' | sed -e 's?/?-?g'`
    SYSTEM=`uname -s | sed -e 's/ //g' | sed -e 's?/?-?g'`
    OS="${MACHINE}-${SYSTEM}"
    if [ -f ../scripts/gnu-os ]
    then	GNUOS=`../scripts/gnu-os 2>/dev/null | sed s/unknown-//`
		if [ "X$GNUOS" != "X" ]
		then	OS=$GNUOS
		fi
    fi
    if [ -f ../../scripts/gnu-os ]
    then	GNUOS=`../../scripts/gnu-os 2>/dev/null | sed s/unknown-//`
		if [ "X$GNUOS" != "X" ]
		then	OS=$GNUOS
		fi
    fi
fi
echo $OS
